# Generated by Django 2.1.15 on 2020-02-28 13:48

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def update_view_permission(apps, schema_editor):
    """
    view permission is coming by default now. But there is minor difference in name with old permission.
    """
    content_type = ContentType.objects.get(app_label="credentials", model="usercredential")
    Permission.objects.filter(content_type=content_type, codename='view_usercredential').update(
        name='Can view user credential',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180730_1726'),
    ]

    operations = [
        migrations.RunPython(code=update_view_permission, reverse_code=migrations.RunPython.noop)
    ]
